### PR TITLE
fix: Address sidebar issue when more than 3 ideas are loaded

### LINKED ISSUE #49: Fix styling so sidebar expands with output container
**Expected:** If the user adds more than 3 ideas, the sidebar should extend downward to match the sizing of the output container.

**Actual:** If the user adds more than 3 ideas, the sidebar does not extend downward to match the sizing of the output container, leaving a chunk of whitespace at the bottom left of the screen.

Image

### PR DESCRIPTION
**Pull request by butlertree**
# Description
Adjusted min height value to the main container and side bar to address the issue with the white space during a page scroll.  

# Contributors
@butlertree (Chris)

# Checklist
- [x] My PR has an appropriately descriptive and concise title.
- [x] My PR has a clear description of all proposed changes.
- [x] My PR denotes any/all team members who contributed to it.
- [x] My code follows the Turing Style Guides and best practices.
- [x] I ran the code locally and verified that there are no visible errors.
- [x] feat: My code is clean and readable, so my teammates can easily review it.
- [x] fix: My PR clearly describes not only the fix itself, but the reason for the fix.
- [x] refactor: My PR clearly describes not only the refactor itself, but the reason for the refactor.

### CODE REVIEW

**Review by ericahagle — CHANGES_REQUESTED** [review]
This looks fantastic, @butlertree! 
Screenshot 2023-09-16 at 4 37 57 PM
Screenshot 2023-09-16 at 4 38 05 PM

My only ask is that you update the title of this PR—I don't think "Feature/clean code" really describes what you're doing here, so it would be great if you can make it a little more descriptive.

**Comment by butlertree** [comment]
I updated the pull request title.

**Comment by ericahagle** [comment]
@butlertree I still think that title is misleading... makes it seem like this is a new feature, when really it's a bug fix. I'd suggest something more along the lines of, "fix: Address sidebar issue when more than 3 ideas are loaded". It doesn't have to be exactly that, of course, but something similar to denote that it was a bug fix and what the issue was.

**Comment by butlertree** [comment]
I updated it.

**Review by ericahagle — APPROVED** [review]
Looks great! 🌮

**Pull request merged**
